config/routes.rb
Rails.application.routes.draw do

  root "corgis#index"

  resources :corgis

end

app/models/corgi.rb
class Corgi < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/corgis_controller.rb
class CorgisController < ApplicationController
  before_action :set_corgi, only: [:show, :edit, :update, :destroy]

  # GET /corgis
  # GET /corgis.json
  def index
    @corgis = Corgi.all
    @matches = @corgis.select { |corgi| corgi.match == true }
    @misses = @corgis.select { |corgi| corgi.match == false }
  end

  # GET /corgis/1
  # GET /corgis/1.json
  def show
  end

  # GET /corgis/new
  def new
    @corgi = Corgi.new
  end

  # GET /corgis/1/edit
  def edit
  end

  # POST /corgis
  # POST /corgis.json
  def create
    @corgi = Corgi.new(corgi_params)

    if @corgi.save
      redirect_to @corgi, notice: 'Corgi was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /corgis/1
  # PATCH/PUT /corgis/1.json
  def update
    if @corgi.update(corgi_params)
      respond_to do |format|
        format.html {redirect_to @corgi, notice:"Corgi was successfully updated"}
      format.json {render json: @corgi}
    end
    else
      respond_to do |format|
        format.html render :edit
        format.json {render json: @corgi}
      end
    end
  end

  # DELETE /corgis/1
  # DELETE /corgis/1.json
  def destroy
    @corgi.destroy

    redirect_to corgis_url, notice: 'Corgi was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corgi
      @corgi = Corgi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corgi_params
      params.require(:corgi).permit(:name, :bio, :match, :profile_img)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corgis_helper.rb
module CorgisHelper
end

app/views/corgis/_form.html.erb
<%= form_for(@corgi) do |f| %>
  <% if @corgi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corgi.errors.count, "error") %> prohibited this corgi from being saved:</h2>

      <ul>
      <% @corgi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :profile_img %><br>
    <%= f.text_field :profile_img %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/corgis/edit.html.erb
<h1>Editing corgi</h1>

<%= render 'form' %>

<%= link_to 'Show', @corgi %> |
<%= link_to 'Back', corgis_path %>

app/views/corgis/index.html.erb
<div class="clearfix">
  <div class="corgi-container" id="misses">
    <h2>Thanks, but No Thanks</h2>
    <ul>
      <% @misses.each do |miss| %>
        <li data-id="<%= miss.id %>" class="corgi" %>
          <h4><%= miss.name %></h4>
          <%= image_tag miss.profile_img, :class => "pic" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="corgi-container" id="candidates">

    <ul>

      <% @corgis.each_with_index do |corgi, i| %>
        <li data-id="<%= corgi.id %>" class="corgi <%= (i == 0) ? 'active' : 'hidden' %>">
          <h3><%= corgi.name %></h3>
          <%= image_tag corgi.profile_img, :class => "pic" %>
          <p class="bio"><%= corgi.bio %></p>
        </li>
      <% end %>

    </ul>

    <button class="choose-corgi" id="paw-left">Paw Left (No, Thanks)</button>
    <button class="choose-corgi" id="paw-right">Paw Right (Yes, Please!)</button>

  </div>

  <div class="corgi-container" id="matches">
    <h2>Matches!</h2>
    <ul>
      <% @matches.each do |match| %>
        <li data-id="<%= match.id %>" class="corgi" %>
          <h4><%= match.name %></h4>
          <%= image_tag match.profile_img, :class => "pic" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div>
  <%= link_to 'New Corgi', new_corgi_path %>
</div>

app/views/corgis/new.html.erb
<h1>New corgi</h1>

<%= render 'form' %>

<%= link_to 'Back', corgis_path %>

app/views/corgis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @corgi.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @corgi.bio %>
</p>

<p>
  <strong>Profile img:</strong>
  <%= image_tag @corgi.profile_img %>
</p>

<p>
  <strong>Match?:</strong>
  <%= @corgi.match %>
</p>

<%= link_to 'Edit', edit_corgi_path(@corgi) %> |
<%= link_to 'Back', corgis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OkCorgi</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>